### ISSUE TITLE
docker exec error

### ISSUE THREAD

**Issue by webmap2015** [lukey78/otm-docker#2]
Hi, 

docker image installation

![docker image installation](https://user-images.githubusercontent.com/10267317/78937446-32eaab80-7ab9-11ea-96a2-88ab25da53db.PNG)
**********
docker log result

![docker log result](https://user-images.githubusercontent.com/10267317/78937749-adb3c680-7ab9-11ea-825a-e0b1010c9978.PNG)
**********
docker exec result

![docker exec result](https://user-images.githubusercontent.com/10267317/78937765-b1dfe400-7ab9-11ea-9c67-7512759f556d.PNG)
**********
docker ps result

![docker ps](https://user-images.githubusercontent.com/10267317/78937311-f323c400-7ab8-11ea-9942-af1a4f310e98.PNG)

Thanks.

**Comment by lukey78** [comment]
The error says you set you activated Let's Encrypt, but didn't specify a valid domain name (it's localhost in your config). For testing I recommend to deactivate Let's Encrypt with LETSENCRYPT=0 environment variable.

**Comment by webmap2015** [comment]
It worked. Thanks.
